# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
    - id: nbqa-black
      additional_dependencies: [ black==25.1.0, jupytext==1.17.3 ]
    - id: nbqa-isort
      additional_dependencies: [ isort==6.0.1, jupytext==1.17.3 ]
      args: [--profile=black]
    - id: nbqa-flake8
      additional_dependencies: [ flake8==7.3.0, jupytext==1.17.3 ]
      args:
        - "--max-line-length=88"
        - "--nbqa-dont-skip-bad-cells"
        - "--extend-ignore=E203"
      exclude: notebook_template.md
    - id: nbqa
      name: nbqa-codespell
      args:
        - "codespell"
        - "--nbqa-md"
        - "--nbqa-shell"
        - "--nbqa-files=.precommit-conf-files/codespell-ignore-words.txt"
        - "-I"
        - ".precommit-conf-files/codespell-ignore-words.txt"

      additional_dependencies: [ codespell==2.4.1, jupytext==1.17.3 ]
