name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - DavidT3
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
#  - type: input
#    id: contact
#    attributes:
#      label: Contact Details
#      description: How can we get in touch with you if we need more info?
#      placeholder: ex. email@example.com
#    validations:
#      required: false
  - type: textarea
    id: particular-file
    attributes:
      label: Is the problem with a particular notebook?
      description: Please let us know which notebook you are having trouble with, if any.
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you experiencing this problem on?
      description: Please let us know where you are running into the issue
      options:
        - Fornax
        - Fornax-Hea image running locally
        - SciServer
        - CI/CD
        - Other
      default: 0
    validations:
      required: true
  - type: textarea
    id: platform-freeform
    attributes:
      label: Other platform
      description: If you answered "Other" to the above question, please describe your platform here.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
